package com.example.sahilgoyal.apnishuttle.serverrequesthandler;

/**
 * Created by sahil.goyal on 4/6/2018.
 */

public enum ResponseTypes {


        LOGIN,MYRIDES,BOOK_RIDE,PAYMENT,GETROUTE,GETTIMING,GETSTOPS,DISTRIBUTOR,DEALER,SUMMARY,PARTNER_TYPE,TOWN,OUTLET,OUTLET_GRAPH,LAST13MONTH,SELLER,SUBMIT_ORDER,PARTNERS,ORDER_PRICING,ORDER_SKU,REGISTER,PLACEORDER,INITFORGOTPASSWORD,FINALFORGOTPASSWORD,CREATEORDER,FINISHFORGOTPASSWORD,GETCATEGORY,GETALLORDERS,NOTIFICATION,GETPROFILE,GETALLROUTES,GETALLPCIKUPS,ADDLOCATION,GETONEADDRESS,ADDADDRESS,GETORDERDETAIL,GETCATEGORIESITEM,GETADDRESSES,GETCATEGORYITEMDETAIL,DRIVERLOCATION,GETPICKUPADDRESS
}

